title: "Egor's Blog"
author: "Egor Andreevich"
description: "Android, Kotlin and other tech"
baseurl: /
url: https://egorand.dev

navbar-links:
  About Me: "about"

social-network-links:
  github: Egorand
  twitter: EgorAnd

share-links-active:
  twitter: true

rss-description: Subscribe via RSS
url-pretty: "egorand.dev"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"

# Build settings
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      readtime: true
